### ISSUE TITLE
Functional Bug(Group 4): Build Sequence is not precisely defined

### ISSUE THREAD

**Issue by shubham-agrawal04** [IITGN-CS431/project-cns#120]
I am using Linux environment inside WSL in Windows, however both the server and the client files, upon execution, separately installs docker which is already running in Linux inside wsl, and then launches Ubuntu.
Sequence followed is: Windows -> WSL -> Ubuntu -> Docker -> Ubuntu   for both the server and client file, which is completely unnecessary, which is taking a lot of unnecessary space and also delaying the testing of application.

**Comment by shubham-agrawal04** [comment]
![image](https://github.com/user-attachments/assets/14124117-c4bf-4054-9f73-b39c09a0486d)

**Comment by dkshjn** [comment]
If the bash file isn’t running on your device, you can manually execute the following commands for both the server and the client:

For the Server:
'''
cd server

# Build the server Docker image
docker build -f Dockerfile.server -t server .

# Run the server container, mapping port 8051
docker run -it --name server -p 8051:8051 server
'''

For the Client:
'''
cd client

# Build the client Docker image
docker build -f Dockerfile.client -t client .

# Run the client container, passing the SERVER_IP as an environment variable
docker run -it --name client -e SERVER_IP="$SERVER_IP" client
'''

Make sure to replace $SERVER_IP with the actual IP of your server.

Now, regarding Docker’s role in this setup: Docker is used to create isolated, reproducible environments for both the server and client components. This is essential because it ensures that the application runs consistently across different systems without depending on the underlying OS configurations. Docker is simply using Ubuntu as a base to standardize the environment, ensuring compatibility and reliability. The only noticeable time delay occurs when Docker images are built initially; once built, subsequent executions are fast and require minimal waiting time.

Your noted sequence—Windows -> WSL -> Ubuntu -> Docker -> Ubuntu—is indeed complex but helps ensure the application’s consistency across different devices and setups, which is particularly useful in development environments where system configurations can vary. This sequence is intentional, not wasteful, and is essential for containerizing the server and client for accurate testing and deployment. It’s not part of a functional bug, so please review your bug criteria accordingly.

**Comment by bichhawat** [comment]
@shubham-agrawal04 Please check if this works, if not get in touch with the team for memory requirements, if that's the issue
