### ISSUE TITLE
SECURITY BUG(GROUP 10) : All log files can be tampered 

### ISSUE THREAD

**Issue by AniketAsati** [IITGN-CS431/project-cns#222]
There is no functionality for client and server interactions on 2 separate machines. Hence, all log files are on the same machine. These are encrypted but can be tampered.
![Screenshot from 2024-10-30 20-27-18](https://github.com/user-attachments/assets/2a398fc4-0c9c-45c0-a0d0-423062f1d268)
Initially, after log append it contains this data.
![Screenshot from 2024-10-30 20-27-06](https://github.com/user-attachments/assets/a5d61785-8ee8-4e9e-8f9b-8ee248979169)
Then if you delete some lines
![Screenshot from 2024-10-30 20-26-35](https://github.com/user-attachments/assets/962ca954-630c-4b4e-932f-246dc57110b1)
And now the logread command doesn't work for that log file.

**Comment by bichhawat** [comment]
If you are able to print random information by modifying the log file, then it would be a bug. If it shows invalid in all cases after being modified, that should be acceptable.

**Comment by Kishan-Ved** [comment]
I had created a similar issue for another group: https://github.com/IITGN-CS431/project-cns/issues/110

This is applicable for all groups without a server and client model.

**Comment by Kishan-Ved** [comment]
This same thing can be reproduced here:

![image](https://github.com/user-attachments/assets/5f0ffc8a-4e85-4e59-8b1d-636bb28f215a)

**Comment by rovin99** [comment]
I don't think there is a need for a client server model here. The system  instead of appending a new hash for each entry in log file what it is doing is creating a hash for entire content(new entry+old entry) so any inconsistency while decrypting would get caught. 

here is one ex:
![DA5CC43A-1D7E-4D3E-A0E5-46364831C029_4_5005_c](https://github.com/user-attachments/assets/0614ebd7-16bf-4803-9907-15765c44f6ae)

![8A69EA54-2A54-41C1-8807-7370151B2708_4_5005_c](https://github.com/user-attachments/assets/b5f87cec-0bf1-4f47-bd0a-3459175411b6)
Now trying to replicate entry in log file 
![C2E5FD35-9F8B-40F0-9C8B-01DA593CE51F_4_5005_c](https://github.com/user-attachments/assets/80e94f12-2ab3-4708-a80b-4c5d6bda9c94)
Gives an Error when reading: 
![F7658E79-1A6D-4761-9265-3045E5DE5D31_4_5005_c](https://github.com/user-attachments/assets/3c470a26-3240-4bbf-ad68-4483bf934085)

Logappend without tempring log file: 
![AA8BA292-21E2-4243-8FEC-9A53299C2A33](https://github.com/user-attachments/assets/79eafd22-ddcf-4143-bf96-7ede61bd1c14) 
Here you can see the hash is totally different since entire content(new entry+old entry) is encrypted.

**Comment by bichhawat** [comment]
Yes, the issue that Kishan has pointed out is a valid issue but if the current model is showing invalid on modifying the log files, that is acceptable.
