### ISSUE TITLE
0.0.0.0 is considered as valid IPv4 address - Group 3

### ISSUE THREAD

**Issue by carbonvibes** [IITGN-CS431/project-cns#230]
When the atm is given the IP address `0.0.0.0`, which is commonly used as a placeholder and not a valid connection target, it attempts to establish a connection and returns a `Connection refused error` instead of a clear validation error. This behavior is inconsistent with how other invalid IP addresses (e.g., `1110.0.0.0`) are handled.

<img width="1306" alt="Screenshot 2024-10-30 at 7 42 00 PM" src="https://github.com/user-attachments/assets/75955262-360f-4ef2-95d4-4cc7fead9023">

How other invalid IP address are handled:
<img width="813" alt="Screenshot 2024-10-30 at 7 42 25 PM" src="https://github.com/user-attachments/assets/819f5020-4b6d-4252-88e5-52e95d5959cb">

Therefore there is a inconsistency in how invalid IP addresses are handled.

**Comment by Quantizate** [comment]
@carbonvibes given the constraints of an IPv4 address, we do believe that `0.0.0.0` is a valid one. Please refer to the stackoverflow thread [link](https://stackoverflow.com/questions/3655723/is-0-0-0-0-a-valid-ip-address). 

`The 0.0.0.0 is used to bind all IPv4 interfaces. So it's a special value just like 127.0.0.1.`  -- Source: Stack Overflow

**Comment by carbonvibes** [comment]
`0.0.0.0`  is used as a placeholder, and it is not an actual IPv4 address that one can connect to. In the context of IPv4 addressing, `0.0.0.0` serves as a non-routable meta-address used primarily in networking to indicate “any IPv4 address.”  However, it cannot be assigned to a specific host or device and doesn’t function like a regular IP address, such as `127.0.0.1`, which signifies localhost, which actually exists and is known as the loopback address. Adding to that, the atm has the same inconsistency when the `255.255.255.255` is used; this is also another IPV4 address to which no host can be assigned.

**Comment by carbonvibes** [comment]
Regarding the IP address connection issue, I  found that changing the openssl.conf did not resolve the problem and also this was not mentioned anywhere in your readme file.

<img width="1364" alt="Screenshot 2024-11-01 at 7 32 56 PM" src="https://github.com/user-attachments/assets/ffb50efc-8325-4415-8648-6977886b14b8">


The fundamental issue remains: the current implementation fails to properly validate non-routable IP addresses like `0.0.0.0`. While you've suggested that this is a valid IP address based on its format and usage in some networking contexts, it is not a legitimate target for connection attempts.

The comparison to uvicorn's use of `0.0.0.0` is misleading. In uvicorn, this address is used for server-side binding to listen on all interfaces - a completely different networking scenario from client-side connection attempts.

The current behavior of attempting to connect and returning a "SSL VERIFICATION BACKEND" error, instead of a generic IP INVALID error (which you have used for all other types of invalid IP) is problematic. It obscures the real issue: you're trying to connect to an address that cannot be connected to. This is not a matter of the connection being refused, but of the address being fundamentally invalid for connection.

The argument that "the client knows the server's actual IP" does not justify bypassing proper input validation. I recommend implementing explicit IP address validation to prevent these connection attempts and provide clear, actionable error messages.

**Comment by pratyush3757** [comment]
> The argument that "the client knows the server's actual IP" does not justify bypassing proper input validation. I recommend implementing explicit IP address validation to prevent these connection attempts and provide clear, actionable error messages.

According to this thread, input is actually being validated for a valid IP address.
For IPv4 `Addresses are fixed length of four octets (32 bits)` Source: [RFC 791 section 2.3, addressing part](https://www.rfc-editor.org/rfc/rfc791#section-2.3)  
The rest of the paragraph about address classes has been replaced by CIDR. [RFC 4632](https://www.rfc-editor.org/rfc/rfc4632.html)
Other than that, I agree that there are reserved addresses according to IANA. There are currently `25` of them. [List link](https://www.iana.org/assignments/iana-ipv4-special-registry/iana-ipv4-special-registry.xhtml) 
We can't expect them to consider all of them in the code, especially when we are just emulating the atm interface. That arg is just there for us to help us connect to the server. 
Also, it's giving us an error when it cannot connect to the server, so it's the expected behaviour. This would be a valid bug if the client leaked info or had unexpected/undefined behaviour on passing reserved addresses.

> the client knows the server's actual IP
This is a valid argument too. Any deployed client will have the bank address hardcoded on the machine.

**Comment by carbonvibes** [comment]
Agreed.
