### ISSUE TITLE
Group 4 (Security & Functional Bug):log data loss issue persists

### ISSUE THREAD

**Issue by cpatel321** [IITGN-CS431/project-cns#257]
Similar to issue   #125, log data is still being lost, this time with a different reason for the server crash. 
![image](https://github.com/user-attachments/assets/333ee853-4773-40b8-a275-5999a63f4c89)
 
In the right terminal, it can be observed that the log data that were present before the crash are lost.

**Comment by cpatel321** [comment]
@aditya-me13 All the log data must be backed up outside the machine to escape from data loss upon crashes.

**Comment by dkshjn** [comment]
The Docker setup is designed to start each session fresh, so previous session data isn’t kept. This isn’t a bug but a feature of the containerized environment, making sure each session begins with a clean slate.

**Comment by dkshjn** [comment]
Your assumption about data loss isn’t accurate. As shown in the screenshots, the server doesn’t lose its data if it’s restarted, even after being stopped or crashing unexpectedly. The stored data persists across sessions unless the server is rebuilt. Rebuilding the Docker image clears the data, which is standard in Docker and should be expected. If you just start the server again without rebuilding, it picks up right where it left off.

To clarify, the server doesn’t lose its data if it’s simply restarted after a crash, even if there’s a slash in the log filename. The screenshots clearly show that restarting the server retains the log data. The only reason data would be lost is if the server is rebuilt, which resets any stored data as part of Docker’s setup. In issue #125, it appears that instead of restarting the server, the command ```./run_server.sh``` was executed, which rebuilds and then starts the server. In this case, only the ```docker start -i server``` command is needed to restart the server after a crash, without rebuilding and thus preserving data.

@bichhawat sir, I’d like it noted that the previously reported security bug in issue #125 was never a bug. The reported bug was incorrect. The only issue that should be considered here is the functional one(client was able to stop the server), which we acknowledge, **while the data loss and security concerns are baseless claims.**

The images have been attached for your reference.

### Server Stopped and Restarted Using ```docker start -i server```
<img width="914" alt="Screenshot 2024-11-14 at 12 47 55 AM" src="https://github.com/user-attachments/assets/a3741d64-a0a2-493e-ae23-9f5c3e33f465">

### Client-Server Interaction Showing Data Persistence After Server Restart

<img width="1295" alt="Screenshot 2024-11-14 at 12 48 28 AM" src="https://github.com/user-attachments/assets/94afbb62-fb20-4dfd-bcff-1c4586dfb506">
<img width="1297" alt="Screenshot 2024-11-14 at 12 48 34 AM" src="https://github.com/user-attachments/assets/abff8cb6-fcb2-414b-a77b-87590930f266">

### Client-Server Interaction with Slash in Log Filename Causing Crash, Followed by Data Persistence After Restart Using ```docker start -i server```

<img width="1263" alt="Screenshot 2024-11-14 at 12 55 24 AM" src="https://github.com/user-attachments/assets/30469eb7-7d11-47fa-9ad1-8a3f02e2c94e">
<img width="1276" alt="Screenshot 2024-11-14 at 12 55 38 AM" src="https://github.com/user-attachments/assets/1ab63b81-7682-4da1-92d8-3e48986894ee">
