### ISSUE TITLE
Prompt Issue [Group 3] : Invalid Card Files

### ISSUE THREAD

**Issue by AshStorm17** [IITGN-CS431/project-cns#91]
![{F2F419F1-2BB7-4A82-9791-7B5FF53FE1F9}](https://github.com/user-attachments/assets/eda529fd-e947-4d47-b10e-810814ed5e67)

I created a bank account and gave the card file as a.

![{EB88A327-BF27-47C4-9A5D-A3BCEB13227D}](https://github.com/user-attachments/assets/9c6cf168-6d6b-4e88-a2cc-0977c0a618fb)

I can see a card file been created.

However, I tried many variations of the card file, but none were accepted.

**Comment by YYashraj** [comment]
1. You need to simply write the cardfile name that you provided during the creation of your account.
2. The reason why none of your commands are working is because you have not logged in to activate a session between that user's account and bank. Refer to the README to understand the command-flow.

No issue otherwise here.
