### ISSUE TITLE
Card Files Issue [Group 3] : Visible Hashes

### ISSUE THREAD

**Issue by AshStorm17** [IITGN-CS431/project-cns#93]
![{61A7845D-D3D1-4BC4-9B8F-20C919FE1EBC}](https://github.com/user-attachments/assets/b37ab0e3-c5ba-4425-8d81-4032570d9e61)

In card files, along with the pin, the encrypted text value is also shown, which can be used to find the encryption key.
If the database is confesscated in some scenario, all the pins can be taken out of the database.

![{3EF53460-812B-4D15-BEC1-53483400771C}](https://github.com/user-attachments/assets/7d1048e9-0299-433e-bd1d-53bfee756eef)
Also, I am able to give the same card values for different transactions, which should not be allowed.

**Comment by Quantizate** [comment]
So our structure is a bit different for the card file, basically this contains <account name>#<hash>. There must a coincidence with the account name and the pin you have chosen because which you might be thinking that the pin is being stored. Please try for other cases too. Also the hash is not correlated to the pin, don't worry your pin is safe with in the server 😁
